### ISSUE TITLE
Unable to run flask from following README.md instructions

### ISSUE THREAD

**Issue by tramyn** [IsabelMarleen/GSOC2020#6]
I tried following this project's README.md file and was unable to run flask using this line of code:
`FLASK_APP=app python -m flask run`

I get "This site can't be reached" when going to this url: http://localhost:5000/
@JMante1 @IsabelMarleen could you look into this and let me know if there are additional setups that I must perform? 
If it turns out that additional setup must be made to get this project running, then I would suggest to expand the README.md file to reflect these additional steps.

**Comment by JMante1** [comment]
Do either of these methods work for you?:
-git clone repository

For anaconda prompt:
- cd to directory
- `set FLASK_APP=app.py`
- `set FLASK_ENV=development`
- `flask run --port 5000`

For terminal:
- cd into directory
- `FLASK_APP=app python -m flask run`

Can then see the site at http://localhost:500/status

**Comment by tramyn** [comment]
If the expected output is to get the following message from running flask, then running the anaconda prompt works:

```
* Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [08/Sep/2020 11:31:29] "GET / HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2020 11:31:29] "GET /favicon.ico HTTP/1.1" 404 -
```

However, I then get the message below when browsing to this url: http://localhost:5000/ 

**Not Found**
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

The terminal instruction gives me this message:
`No module named flask`

**Comment by JMante1** [comment]
Note that the endpoint http://localhost:5000/ doesn't exist so try instead going to http://loaclhost:5000/status and that should work for the anaconda.

Try instead for Unix Bash (Linux, Mac, etc.):
- cd into folder
- `pip install -r requirements.txt`
- `export FLASK_APP=app`
- `flask run`

**Comment by tramyn** [comment]
Awesome! Those set of instructions worked. Please, could the README.md get updated to reflect these additional steps?

**Comment by IsabelMarleen** [comment]
This repository is no longer maintained so all issues should be directed to the appropriate [repository](https://github.com/SynBioHub/Plugin-Submit-Excel2SBOL). Unless the plugin structure has fundamentally changed, it seems the readme still incorrectly directs the user to the endpoint http://localhost:5000/ instead of http://localhost:5000/status. I have thus opened a new issue in the appropriate place.
