### ISSUE TITLE
Clarify README.md instructions for "Testing" Section

### ISSUE THREAD

**Issue by tramyn** [IsabelMarleen/GSOC2020#7]
I'm not sure what the "Testing" section is really testing and request that the README.md should have a more detailed explanation on what specifically the "Testing" section is referring to. From reading the block of code, I understand that a dictionary `run_manifest' is setting desired file properties. But, the instruction does not tell me what the block of code is testing and what to expect when executing this block of code.

**Comment by IsabelMarleen** [comment]
Issue is a duplicate of this issue [here](https://github.com/SynBioHub/Plugin-Submit-Excel-Library/issues/2) that was solved.
